<a href="https://colab.research.google.com/github/danvasem/pytorch-ex/blob/master/Clase2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import torch
import numpy as np

Trabajando con Tensores

In [3]:
torch.__version__

'1.5.1+cu101'

In [4]:
tensor_a=torch.ones(2,2)
tensor_a

tensor([[1., 1.],
        [1., 1.]])

In [6]:
tensor_b=torch.Tensor(2,2)
print(tensor_b)
tensor_b.uniform_(0,1)

tensor([[2.3998e-35, 0.0000e+00],
        [1.5414e-43, 1.6115e-43]])


tensor([[0.5764, 0.5300],
        [0.5107, 0.8194]])

In [9]:
tensor_c=torch.rand(2,2)
tensor_c

tensor([[0.1075, 0.4916],
        [0.4917, 0.8105]])

In [10]:
result = tensor_b + tensor_c
result

tensor([[0.6839, 1.0217],
        [1.0024, 1.6298]])

In [12]:
result.shape
reshaped = result.view(4,1)
reshaped

tensor([[0.6839, 1.0217, 1.0024, 1.6298]])

In [14]:
points = torch.tensor([[1.0,2.0],[3.0,4.0]])
points.storage()

 1.0
 2.0
 3.0
 4.0
[torch.FloatStorage of size 4]

In [16]:
points, points.stride()

(tensor([[1., 2.],
         [3., 4.]]), (2, 1))

In [17]:
p_t=points.t()
p_t, p_t.stride()

(tensor([[1., 3.],
         [2., 4.]]), (1, 2))

In [19]:
tensor_x = torch.tensor([1,2,3,4])
torch.unsqueeze(tensor_x,0)

tensor([[1, 2, 3, 4]])

In [22]:
numpyArray = np.random.randn(2,2)
torch.from_numpy(numpyArray)

tensor([[-1.4319, -1.1264],
        [-0.2659, -0.4723]], dtype=torch.float64)