<a href="https://colab.research.google.com/github/danvasem/pytorch-ex/blob/master/Clase2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [33]:
import torch
import numpy as np
import pandas as pd

#Trabajando con Tensores









In [4]:
torch.__version__

'1.5.1+cu101'

In [5]:
tensor_a=torch.ones(2,2)
tensor_a

tensor([[1., 1.],
        [1., 1.]])

In [6]:
tensor_b=torch.Tensor(2,2)
print(tensor_b)
tensor_b.uniform_(0,1)

tensor([[3.2729e-36, 0.0000e+00],
        [3.7835e-44, 0.0000e+00]])


tensor([[0.1327, 0.7832],
        [0.0443, 0.1478]])

In [7]:
tensor_c=torch.rand(2,2)
tensor_c

tensor([[0.9290, 0.0695],
        [0.8604, 0.3481]])

In [8]:
result = tensor_b + tensor_c
result

tensor([[1.0616, 0.8527],
        [0.9047, 0.4959]])

In [9]:
result.shape
reshaped = result.view(4,1)
reshaped

tensor([[1.0616],
        [0.8527],
        [0.9047],
        [0.4959]])

In [10]:
points = torch.tensor([[1.0,2.0],[3.0,4.0]])
points.storage()

 1.0
 2.0
 3.0
 4.0
[torch.FloatStorage of size 4]

In [11]:
points, points.stride()

(tensor([[1., 2.],
         [3., 4.]]), (2, 1))

In [12]:
p_t=points.t()
p_t, p_t.stride()

(tensor([[1., 3.],
         [2., 4.]]), (1, 2))

In [13]:
tensor_x = torch.tensor([1,2,3,4])
torch.unsqueeze(tensor_x,0)

tensor([[1, 2, 3, 4]])

In [21]:
numpyArray = np.random.randn(2,2)
from_numpy=torch.from_numpy(numpyArray)
from_numpy

tensor([[-0.5393,  0.5463],
        [-0.7963,  0.0320]], dtype=torch.float64)

#Representar datos con Tensores

En el siguiente ejemplo las dimensiones dim=0 significa que se suman las filas, es decir, el recorrido de la suma es hacia abajo, para el dim=1 se suman las columnas, es decir, el recorrido de la suma es hacia la izquierda. Dim=2 no aplicaría porque en esta matriz no hay 3 dimensiones. Si no se especifica nada, entonces la suma es total de todos los elementos.

In [27]:
print(from_numpy)
print(torch.sum(from_numpy))
print(torch.sum(from_numpy,dim=0))
print(torch.sum(from_numpy,dim=1))

tensor([[-0.5393,  0.5463],
        [-0.7963,  0.0320]], dtype=torch.float64)
tensor(-0.7574, dtype=torch.float64)
tensor([-1.3357,  0.5783], dtype=torch.float64)
tensor([ 0.0070, -0.7644], dtype=torch.float64)


In [28]:
print(from_numpy)
print(torch.mean(from_numpy))
print(torch.mean(from_numpy,dim=0))
print(torch.mean(from_numpy,dim=1))

tensor([[-0.5393,  0.5463],
        [-0.7963,  0.0320]], dtype=torch.float64)
tensor(-0.1894, dtype=torch.float64)
tensor([-0.6678,  0.2891], dtype=torch.float64)
tensor([ 0.0035, -0.3822], dtype=torch.float64)


Para calcular la deviación estandard:

In [29]:
print(from_numpy)
print(torch.std(from_numpy))
print(torch.std(from_numpy,dim=0))
print(torch.std(from_numpy,dim=1))

tensor([[-0.5393,  0.5463],
        [-0.7963,  0.0320]], dtype=torch.float64)
tensor(0.6003, dtype=torch.float64)
tensor([0.1817, 0.3637], dtype=torch.float64)
tensor([0.7677, 0.5857], dtype=torch.float64)


Guardar el tensor

In [30]:
torch.save(from_numpy,'tensor.t')

Cargar el tensor

In [32]:
load=torch.load('tensor.t')
load

tensor([[-0.5393,  0.5463],
        [-0.7963,  0.0320]], dtype=torch.float64)

In [35]:
url='https://raw.githubusercontent.com/amanthedorkknight/fifa18-all-player-statistics/master/2019/data.csv'
dataframe = pd.read_csv(url)
dataframe

Unnamed: 0      ID  ... GKReflexes  Release Clause
0               0  158023  ...        8.0         €226.5M
1               1   20801  ...       11.0         €127.1M
2               2  190871  ...       11.0         €228.1M
3               3  193080  ...       94.0         €138.6M
4               4  192985  ...       13.0         €196.4M
...           ...     ...  ...        ...             ...
18202       18202  238813  ...        9.0           €143K
18203       18203  243165  ...       12.0           €113K
18204       18204  241638  ...       13.0           €165K
18205       18205  246268  ...        9.0           €143K
18206       18206  246269  ...        9.0           €165K

[18207 rows x 89 columns]

In [36]:
dataframe.columns

Index(['Unnamed: 0', 'ID', 'Name', 'Age', 'Photo', 'Nationality', 'Flag',
       'Overall', 'Potential', 'Club', 'Club Logo', 'Value', 'Wage', 'Special',
       'Preferred Foot', 'International Reputation', 'Weak Foot',
       'Skill Moves', 'Work Rate', 'Body Type', 'Real Face', 'Position',
       'Jersey Number', 'Joined', 'Loaned From', 'Contract Valid Until',
       'Height', 'Weight', 'LS', 'ST', 'RS', 'LW', 'LF', 'CF', 'RF', 'RW',
       'LAM', 'CAM', 'RAM', 'LM', 'LCM', 'CM', 'RCM', 'RM', 'LWB', 'LDM',
       'CDM', 'RDM', 'RWB', 'LB', 'LCB', 'CB', 'RCB', 'RB', 'Crossing',
       'Finishing', 'HeadingAccuracy', 'ShortPassing', 'Volleys', 'Dribbling',
       'Curve', 'FKAccuracy', 'LongPassing', 'BallControl', 'Acceleration',
       'SprintSpeed', 'Agility', 'Reactions', 'Balance', 'ShotPower',
       'Jumping', 'Stamina', 'Strength', 'LongShots', 'Aggression',
       'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure',
       'Marking', 'StandingTackle', 'SlidingT

In [62]:
subset = dataframe[['Overall', 'Age','International Reputation', 'Weak Foot',
       'Skill Moves']].dropna(axis=0, how='any')
columns = subset.columns[1:]
players= torch.tensor(subset.values).float()
players.shape, players.type()

(torch.Size([18159, 5]), 'torch.FloatTensor')

In [63]:
data = players[:,1:]
data, data.shape

(tensor([[31.,  5.,  4.,  4.],
         [33.,  5.,  4.,  5.],
         [26.,  5.,  5.,  5.],
         ...,
         [16.,  1.,  3.,  2.],
         [17.,  1.,  3.,  2.],
         [16.,  1.,  3.,  2.]]), torch.Size([18159, 4]))

In [64]:
target = players[:,0]
target, target.shape

(tensor([94., 94., 92.,  ..., 47., 47., 46.]), torch.Size([18159]))

In [65]:
mean = torch.mean(data, dim=0)
mean

tensor([25.1225,  1.1132,  2.9473,  2.3613])

In [66]:
std = torch.std(data, dim=0)
std

tensor([4.6706, 0.3940, 0.6605, 0.7562])

Normalizar = restandole la media a cada dato y dividiendo para la desviacion estandard

In [77]:
norm = (data - mean) / std
norm

tensor([[ 1.2584,  9.8641,  1.5939,  2.1671],
        [ 1.6866,  9.8641,  1.5939,  3.4896],
        [ 0.1879,  9.8641,  3.1080,  3.4896],
        ...,
        [-1.9532, -0.2873,  0.0798, -0.4778],
        [-1.7391, -0.2873,  0.0798, -0.4778],
        [-1.9532, -0.2873,  0.0798, -0.4778]])

In [76]:
stdN=torch.std(norm,dim=0)
stdN

tensor([1.0000, 1.0000, 1.0000, 1.0000])

In [84]:
good=data[torch.ge(target,85)]
avarage = data[torch.gt(target,70) & torch.lt(target,85)]
notSoGood=data[torch.le(target,70)]

goodMean = torch.mean(good,dim=0)
avarageMean = torch.mean(avarage,dim=0)
notSoGoodMean = torch.mean(notSoGood,dim=0)

goodMean, avarageMean, notSoGoodMean

for i, args in enumerate(zip(columns, goodMean, avarageMean, notSoGoodMean)):
  print('{:25} {:6.2f} {:6.2f} {:6.2f}'.format(*args))

Age                        28.35  27.23  24.37
International Reputation    3.38   1.36   1.01
Weak Foot                   3.45   3.11   2.89
Skill Moves                 3.04   2.75   2.22
